language: node_js
node_js:
- 0.8
env:
  global:
  - GH_OWNER: JulianMayorga
  - GH_PROJECT_NAME: ngBlog
  - secure: BH1lVS5a1vrkcj4qwCspKlLjpKPrSgdrOGwNoAockM66Jp7UNNQxBDWtxyZ5pQxrpamBJBp7RkOrFbSNCKLFNDqqYpsLKaei0sQTSEdbI4IlQhfKQFE3YxyB0Dd+Ss+m9aV5T1/F5ZWrtB5w2IzUQtO6OKD3WoelsImas1qiYSI=
before_script:
- npm install -g grunt-cli bower
script:
- bower install
- npm test
after_success:
- git config user.email "mayorga.julian@gmail.com"
- git config user.name "ElJuli"
- grunt build
- grunt gh-pages
