language: node_js
node_js:
- '0.8'
- '0.10'
before_script:
- npm install -g bower grunt-cli
- bower install
env:
  global:
  - secure: fRJ50qlanbFDgphahl2Mgg+8xxSN46T0zv8/y350CtZJG6tKhmOtNkNZV195V2MB87OUYKUl4tuOTPkhbvoHhEGSlML33OpBMJy7JXPyl7kyN6RlDlL3G5M2pv7wbKWSBu7hJnIrpARwzrYw75JPxTeJ6xlggIjkPJqF6m01veo=
after_success:
- git config --global user.email "mayorga.julian@gmail.com"
- git config --global user.name "ElJuli"
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- grunt build
- grunt gh-pages
