language: node_js
node_js:
- '0.8'
- '0.10'
before_script:
- npm install -g bower grunt-cli
- bower install
env:
  global:
    secure: CE5wdWlPwYoRo8aLZAjZQlnnUYCxSHOmkdUvqEfdDcIxAul3+goen8mcvb36Hpu5tq1WzYG8x9VNxmBQ8VeJQfMFUHjhMWfF9GOCoGzyWrYq/LJGyoW6x+Gifr8EUqqJMoOQBenTZwNClyUdJvxW3LStRCLLBWAueMaP4uas/aU=
after_success:
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - node ./node_modules/grunt-cli/bin/grunt build
  - node ./node_modules/grunt-cli/bin/grunt gh-pages
